export const posts = [
  { slug: "how-to-make-perfume-last", title: "How to make your perfume last all day", date: "2 Oct 2026", tint: "#e8a3b8", excerpt: "Moisturise first, spray pulse points, never rub your wrists.", body: ["Fragrance clings to hydrated skin, so apply an unscented lotion before you spray. Dry skin drinks perfume and lets it fade in a couple of hours.", "Spray on pulse points: wrists, neck and inner elbows. Rubbing your wrists together crushes the top notes, so let it dry on its own.", "Store bottles away from sunlight and bathrooms. Heat and light break down the oils faster than anything else."] },
  { slug: "attar-vs-edp", title: "Attar vs eau de parfum: what's the difference?", date: "24 Sep 2026", tint: "#e6b04f", excerpt: "One is oil-based and intimate, the other is alcohol-based and projects.", body: ["Attars are concentrated perfume oils, traditionally distilled into sandalwood oil. They stay close to the skin and can last 12 hours or more.", "Eau de parfum is diluted in alcohol, which lifts the scent into the air. It projects more, so it suits offices and evenings out.", "Many of our customers wear both: an attar for daytime and an EDP for the evening."] },
  { slug: "understanding-scent-families", title: "A simple guide to scent families", date: "15 Sep 2026", tint: "#8ec5e0", excerpt: "Floral, woody, fresh, oriental. Find the family you keep reaching for.", body: ["Florals are built on rose, jasmine and peony. Woody scents lean on oud, cedar and sandalwood. Fresh scents use citrus, mint and sea notes.", "Oriental perfumes are warm and spicy, with amber, vanilla and incense. They are heavy, rich and best in cooler weather.", "If you are unsure, start with our Discovery Set and see which of the five you reach for first."] },
  { slug: "gifting-perfume", title: "How to pick a perfume as a gift", date: "3 Sep 2026", tint: "#b9a2d6", excerpt: "A safe, thoughtful way to choose for someone else.", body: ["Notice what they already wear and stay inside that family. A new bottle in a familiar style almost always lands well.", "If you don't know, choose a fresh or woody unisex scent, or a gift set so they can discover a favourite.", "Add a handwritten note. It is the cheapest way to make a bottle feel personal."] },
];
export const faqs = [
  ["Are your perfumes authentic?", "Yes. Every bottle is sourced directly from the house and ships sealed with a batch code."],
  ["How long does delivery take?", "3 to 6 working days across India. Express delivery is 1 to 2 days in metro cities."],
  ["Do you ship internationally?", "Yes, to 30+ countries. International delivery takes 7 to 12 working days."],
  ["What is your return policy?", "Unused, sealed bottles can be returned within 30 days for a full refund."],
  ["Do you offer cash on delivery?", "Yes, on orders up to ₹10,000 within India."],
  ["How do I know which scent suits me?", "Start with the Discovery Set, or write to us. We will recommend three bottles."],
  ["How should I store my perfume?", "Keep it in a cool, dark place, away from direct sunlight and bathroom humidity."],
  ["Can I gift wrap my order?", "Gift sets come wrapped. For single bottles, add a gift note at checkout."],
];
export const policies: Record<string, { title: string; sections: [string, string][] }> = {
  "shipping-returns": { title: "Shipping and returns", sections: [["Shipping", "Orders ship within 24 hours. Standard delivery takes 3 to 6 working days. Shipping is free above ₹3,999 and ₹149 below that."], ["Returns", "Return unused, sealed bottles within 30 days of delivery for a full refund to your original payment method."], ["Damaged items", "If a bottle arrives damaged, email us a photo within 48 hours and we will send a replacement."]] },
  privacy: { title: "Privacy policy", sections: [["What we collect", "We collect the details you give us at checkout: name, email, phone and delivery address."], ["How we use it", "To process your order, send updates and, only if you opt in, share new releases. We never sell your data."], ["Your choices", "Write to care@perfumedarbar.in to access, correct or delete your data."]] },
  terms: { title: "Terms of service", sections: [["Orders", "An order is confirmed once payment is received or a cash-on-delivery order is accepted."], ["Pricing", "Prices are in Indian rupees and include GST. We may correct pricing errors before dispatch."], ["Liability", "Our liability is limited to the value of the order. Perfumes should be patch-tested before use."]] },
};
